# Generated by Django 2.0.3 on 2018-04-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180405_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='office',
            new_name='ofice',
        ),
    ]
