# Generated by Django 2.0.3 on 2018-04-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180405_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='coredata',
            name='on_main',
            field=models.BooleanField(default=True, verbose_name='На главной'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='home',
            field=models.CharField(blank=True, max_length=10, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='mail',
            field=models.CharField(blank=True, max_length=20, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='ofice',
            field=models.CharField(blank=True, max_length=10, verbose_name='Офис'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone_1',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон 1'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон 2'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='street',
            field=models.CharField(blank=True, max_length=100, verbose_name='Улица'),
        ),
    ]
