# Generated by Django 2.0.4 on 2018-04-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180405_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('slug', models.SlugField(verbose_name='Метка')),
                ('usort', models.PositiveSmallIntegerField(default=1, verbose_name='Сортировка')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное')),
            ],
        ),
    ]
