# Generated by Django 2.0.4 on 2018-04-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mainmenu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainmenu',
            options={'verbose_name': 'Главное меню', 'verbose_name_plural': 'Главное меню'},
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='to_publish',
            field=models.BooleanField(default=True, verbose_name='Опубликовать'),
        ),
    ]
