# Generated by Django 2.0.4 on 2018-04-06 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180406_0925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainmenu',
            options={'ordering': ['usort'], 'verbose_name': 'Главное меню', 'verbose_name_plural': 'Главное меню'},
        ),
        migrations.RemoveField(
            model_name='coredata',
            name='on_main',
        ),
        migrations.AddField(
            model_name='coredata',
            name='to_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.MainMenu', verbose_name='Прицепить к меню'),
        ),
        migrations.AlterField(
            model_name='coredata',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
    ]
