# Generated by Django 2.0.4 on 2018-04-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180406_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coredata',
            name='to_menu',
            field=models.CharField(blank=True, choices=[(1, 'Главное'), (2, 'Мебель'), (3, 'Материалы'), (4, 'Блог'), (5, 'О себе')], max_length=10, null=True, verbose_name='Прицепить к меню'),
        ),
        migrations.DeleteModel(
            name='MainMenu',
        ),
    ]
