# Generated by Django 2.0.3 on 2018-04-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180429_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coredata',
            name='to_menu',
            field=models.CharField(blank=True, choices=[('main', 'Главное'), ('mebel', 'Мебель'), ('materials', 'Материалы'), ('blog', 'Блог'), ('about', 'О себе')], max_length=10, null=True, verbose_name='Прицепить к меню'),
        ),
    ]
