# Generated by Django 2.0.3 on 2018-04-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180430_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='sl', max_length=200, unique=True, verbose_name='url статьи'),
            preserve_default=False,
        ),
    ]
